name: RBans
version: 0.3
main: net.zxq.rastrosgonegriefing.rbans.RBans
website: http://dev.bukkit.org/server-mods/rbans
commands:
    ban:
       description: Bans a player from the server
       usage: /ban <player>
    unban:
       description: Pardons a player from the server
       usage: /unban <player>
    kick:
       description: Kicks a player from the server
       usage: /kick <player>
    rollbackban:
       description: Bans and rollbacks a player from the server
       usage: /rollbackban <player>
    mute:
       description: Mutes a player from the server
       usage: /mute <player>
    unmute:
       description: Un-Mutes a player from the server
       usage: /unmute <player>
    tempban:
      description: Used to temporarily ban online players.
      usage: /tempban <player> <amount> <unit>
    rframe:
      description: Opens the admin frame for RBans.
      usage: /rframe
    info:
      description: Returns information about the selected player.
      usage: /info <player>
    rbans rb:
      description: Returns information about the selected player.
      usage: /rbans rb <player> <event> <world>